from typing import Any, Callable, Collection, Dict, List

from starlette.types import ASGIApp, Scope

from starlite import Starlite
from starlite.routes import BaseRoute

class RouteMap:
    def __init__(self) -> None: ...
    def add_routes(self, routes: Collection[BaseRoute], app: Starlite) -> None: ...
    def resolve_route(
        self, scope: Scope, parse_path_params: Callable[[List[Dict[str, Any]], List[str]], Dict[str, Any]]
    ) -> ASGIApp: ...
    def add_static_path(self, path: str) -> None: ...
    def is_static_path(self, path: str) -> bool: ...
    def remove_static_path(self, path: str) -> bool: ...
